In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("C:\\Users\\himanshu\\Downloads\\cars.csv")
df

brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

# OHE using Pandas

In [3]:
pd.get_dummies(df,columns=['fuel','owner'],dtype = int)

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

# Dealing with Dummy Trap

In [4]:
pd.get_dummies(df,columns=['fuel','owner'],dtype = int,drop_first =True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

# OneHotEncoding using Sklearn

In [5]:
x = df.iloc[:,0:4]

In [6]:
x.head()

brand  km_driven    fuel         owner
0   Maruti     145500  Diesel   First Owner
1    Skoda     120000  Diesel  Second Owner
2    Honda     140000  Petrol   Third Owner
3  Hyundai     127000  Diesel   First Owner
4   Maruti     120000  Petrol   First Owner

In [9]:
y = df.iloc[:,-1]

In [10]:
y.head()

0    450000
1    370000
2    158000
3    225000
4    130000
Name: selling_price, dtype: int64

In [14]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop="first",sparse_output=False,dtype = np.int32)

In [15]:
x_new = ohe.fit_transform(x[["fuel","owner"]])

print(x_new)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 1]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [16]:
# converting to DataFrame
encoded_columns = ohe.get_feature_names_out(['fuel','owner'])
x_new_df = pd.DataFrame(x_new,columns = encoded_columns)

# Displaying the DataFrame
x_new_df.head()

fuel_Diesel  fuel_LPG  fuel_Petrol  owner_Fourth & Above Owner  \
0            1         0            0                           0   
1            1         0            0                           0   
2            0         0            1                           0   
3            1         0            0                           0   
4            0         0            1                           0   

   owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                   0                     0                  0  
1                   1                     0                  0  
2                   0                     0                  1  
3                   0                     0                  0  
4                   0                     0                  0